# Source: kuberhealthy/templates/clusterrole.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  name: kuberhealthy-daemonset-khcheck
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
