# Source: kuberhealthy/templates/clusterrole.yaml
apiVersion: "rbac.authorization.k8s.io/v1"
kind: ClusterRole
metadata:
  name: kuberhealthy
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - comcast.github.io
    resources:
      - khstates
      - khchecks
      - khjobs
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
      - componentstatuses
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
