# Source: kuberhealthy/templates/khcheck-deployment.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployment-sa
  namespace: kuberhealthy
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
