# Source: kuberhealthy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuberhealthy
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: kuberhealthy
  namespace: kuberhealthy
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
    meta.helm.sh/release-name: 'kuberhealthy'
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: http
  selector:
    app: kuberhealthy
