# Source: kuberhealthy/templates/khcheck-network-connection.yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: network-connection-check
  namespace: kuberhealthy
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  runInterval: 30m
  timeout: 10m
  podSpec:
    containers:
      - name: deployment
        image: kuberhealthy/network-connection-check:v0.1.3
        imagePullPolicy: IfNotPresent
        env:
          - name: CONNECTION_TARGET
            value: "tcp://github.com:443"
        resources:
          requests:
            cpu: 10m
            memory: 5Mi
        restartPolicy: Never
