# Source: jx-kh-check/templates/jx-secrets-check.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jx-secrets-sa
  namespace: kuberhealthy
  annotations:
    meta.helm.sh/release-name: 'jx-kh-check'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
