# Source: jx-kh-check/templates/jx-secrets-check.yaml
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: jx-secrets
  annotations:
    docs.jenkins-x.io: https://jenkins-x.io/v3/admin/troubleshooting/secrets/
    meta.helm.sh/release-name: 'jx-kh-check'
  namespace: kuberhealthy
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  runInterval: 60s
  timeout: 5m
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - env:
        image: ghcr.io/jenkins-x/jx-secrets:0.0.78
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    serviceAccountName: jx-secrets-sa
