# Source: jx-kh-check/templates/jx-webhook-events-check.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jx-webhook-events-service-role
  namespace: jx
  annotations:
    meta.helm.sh/release-name: 'health-checks-jx'
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - get
      - list
