# Source: kuberhealthy/crds/khcheck.yaml---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: khchecks.comcast.github.io
  annotations:
    meta.helm.sh/release-name: 'kuberhealthy'
  labels:
    gitops.jenkins-x.io/pipeline: 'customresourcedefinitions'
spec:
  group: comcast.github.io
  version: v1
  scope: Namespaced
  names:
    plural: khchecks
    singular: khcheck
    kind: KuberhealthyCheck
    shortNames:
      - khc
